[test]
root = "./apps/app"
preload = ["./apps/app/__tests__/preload.ts"]

[install]
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200 # seconds
minimumReleaseAgeExcludes = ["@shadcn/react"]
