"use client";

import { Kbd } from "@repo/design-system/components/ui/kbd";
import { cn } from "@repo/design-system/lib/utils";
import { FileText } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

import { consumeContextTransferFromFragment } from "@/app/_components/context-transfer/client";
import {
	createAudioRecordingsFromTransferPayload,
	createUploadedFilesFromTransferPayload,
} from "@/app/_components/context-transfer/hydrate";
import type {
	AudioRecording,
	UploadedContextFile,
} from "@/app/_components/input-context/types";
import { getPromptHarnessTargetField } from "@/orpc/scribe/prompts";
import type { PromptHarnessId } from "@/orpc/scribe/prompts";

import { DoctorsNoteAgentPanel } from "./doctors-note-agent-panel";
import { DoctorsNoteFieldCard } from "./doctors-note-field-card";
import { DoctorsNoteSection } from "./doctors-note-section";
import type { DoctorsNoteSectionConfig } from "./doctors-note-section";

// Editor height for paired rows. Chosen so the textarea is at least as tall as
// the adjacent info card, never shorter.
const PAIR_MIN_HEIGHT = 300;
const FIELD_CARD_CLASS = "w-full shrink-0 lg:w-72 xl:w-80";

/**
 * A resolved section of a Brief-Baukasten editor. Each section is generated by
 * a prompt harness; when an AI Vorlage (`formId`) drives it, generation streams
 * through that form (harness + template), otherwise the harness's standard
 * template is used.
 */
interface DoctorsNoteEditorSection {
	/** Canonical key (also the harness id), e.g. "diagnosis" | "befunde". */
	key: string;
	label: string;
	harness: PromptHarnessId;
	formId?: string | null;
	templateId?: string | null;
}

interface DoctorsNoteEditorProps {
	title: string;
	description: string;
	sections: DoctorsNoteEditorSection[];
	/** Optional callback when section values change. */
	onValuesChange?: (values: Record<string, string>) => void;
	/** Optional initial values for sections (keyed by section key). */
	initialValues?: Record<string, string>;
	/** Whether the editor is disabled (e.g. during a global loading state). */
	disabled?: boolean;
}

interface CompiledSection extends DoctorsNoteSectionConfig {
	harness: PromptHarnessId;
	templateId?: string | null;
}

interface InitialAgentContext {
	audioRecordings: AudioRecording[];
	contextFiles: UploadedContextFile[];
}

/**
 * Compile resolved sections into the rendered section configs. The harness
 * drives the label/target-field; sibling sections feed in as context keyed by
 * their canonical target field, and a section's own text is the main input
 * (`notes`) on the wire. A section with a `formId` streams through that form.
 */
const compileEditorSections = (sections: DoctorsNoteEditorSection[]): CompiledSection[] =>
	sections.map((section) => ({
		buildPrompt: (notes, context) => {
			const body: Record<string, unknown> = { notes };
			for (const sibling of sections) {
				if (sibling.key === section.key) {
					continue;
				}
				const value = context[sibling.key];
				if (value && value.trim().length > 0) {
					body[getPromptHarnessTargetField(sibling.harness)] = value;
				}
			}
			return body;
		},
		documentType: section.harness,
		formId: section.formId ?? undefined,
		harness: section.harness,
		id: section.key,
		label: section.label,
		placeholder: `${section.label} eingeben oder diktieren …`,
		templateId: section.templateId ?? null,
	}));

export const DoctorsNoteEditor = ({
	title,
	description,
	sections: sectionInput,
	onValuesChange,
	initialValues = {},
	disabled = false,
}: DoctorsNoteEditorProps) => {
	const sections = useMemo(() => compileEditorSections(sectionInput), [sectionInput]);

	const [sectionValues, setSectionValues] = useState<Record<string, string>>(() => {
		const values: Record<string, string> = {};
		for (const section of sections) {
			values[section.id] = initialValues[section.id] || "";
		}
		return values;
	});
	const [initialAgentContext, setInitialAgentContext] = useState<InitialAgentContext | null>(null);
	const hasHydratedTransferRef = useRef(false);

	useEffect(() => {
		if (hasHydratedTransferRef.current) {
			return;
		}
		hasHydratedTransferRef.current = true;

		const hydrateTransfer = async () => {
			try {
				const payload = await consumeContextTransferFromFragment();
				if (!payload) {
					return;
				}

				setSectionValues((prev) => {
					const next = { ...prev };
					for (const section of sections) {
						const targetField = getPromptHarnessTargetField(section.harness);
						const value = payload.textContext[targetField];
						if (typeof value === "string" && value.trim().length > 0) {
							next[section.id] = value;
						}
					}
					onValuesChange?.(next);
					return next;
				});
				setInitialAgentContext({
					audioRecordings: createAudioRecordingsFromTransferPayload(payload),
					contextFiles: createUploadedFilesFromTransferPayload(payload),
				});
				toast.success("Kontext übernommen");
			} catch (error) {
				console.error("Failed to hydrate workspace context transfer:", error);
				toast.error("Kontext konnte nicht übernommen werden.");
			}
		};

		void hydrateTransfer();
	}, [onValuesChange, sections]);

	const handleSectionChange = useCallback(
		(sectionId: string, value: string) => {
			setSectionValues((prev) => {
				const next = { ...prev, [sectionId]: value };
				onValuesChange?.(next);
				return next;
			});
		},
		[onValuesChange],
	);

	const sectionChangeHandlers = useMemo(() => {
		const handlers: Record<string, (value: string) => void> = {};
		for (const section of sections) {
			handlers[section.id] = (value: string) => {
				handleSectionChange(section.id, value);
			};
		}
		return handlers;
	}, [sections, handleSectionChange]);

	// Agent edits are staged as per-section proposals, reviewed via the diff
	// editor (accept/reject) rather than applied directly.
	const [agentProposals, setAgentProposals] = useState<Record<string, string>>({});
	const [pendingSuggestionValues, setPendingSuggestionValues] = useState<Record<string, string>>({});

	const handleAgentPropose = useCallback((sectionId: string, content: string) => {
		setAgentProposals((prev) => ({ ...prev, [sectionId]: content }));
		setPendingSuggestionValues((prev) => ({ ...prev, [sectionId]: content }));
	}, []);

	const handleProposalResolved = useCallback((sectionId: string) => {
		setAgentProposals((prev) => {
			if (!(sectionId in prev)) {
				return prev;
			}
			return Object.fromEntries(Object.entries(prev).filter(([id]) => id !== sectionId));
		});
		setPendingSuggestionValues((prev) => {
			if (!(sectionId in prev)) {
				return prev;
			}
			return Object.fromEntries(Object.entries(prev).filter(([id]) => id !== sectionId));
		});
	}, []);

	const handleSuggestionValueChange = useCallback((sectionId: string, value: string | null) => {
		setPendingSuggestionValues((prev) => {
			if (value === null) {
				if (!(sectionId in prev)) {
					return prev;
				}
				return Object.fromEntries(Object.entries(prev).filter(([id]) => id !== sectionId));
			}
			if (prev[sectionId] === value) {
				return prev;
			}
			return { ...prev, [sectionId]: value };
		});
	}, []);

	const proposalResolvedHandlers = useMemo(() => {
		const handlers: Record<string, () => void> = {};
		for (const section of sections) {
			handlers[section.id] = () => {
				handleProposalResolved(section.id);
			};
		}
		return handlers;
	}, [sections, handleProposalResolved]);

	const effectiveSectionValues = useMemo(() => {
		const values = { ...sectionValues };
		for (const [sectionId, suggestion] of Object.entries(pendingSuggestionValues)) {
			values[sectionId] = suggestion;
		}
		return values;
	}, [pendingSuggestionValues, sectionValues]);

	// Context for a section = the other sections' values, keyed by section id.
	const getContextForSection = useCallback(
		(sectionId: string): Record<string, string> => {
			const context: Record<string, string> = {};
			for (const section of sections) {
				if (section.id !== sectionId && effectiveSectionValues[section.id]) {
					context[section.id] = effectiveSectionValues[section.id];
				}
			}
			return context;
		},
		[effectiveSectionValues, sections],
	);

	const agentSections = sections.map((section) => ({
		content: effectiveSectionValues[section.id] || "",
		formId: section.formId,
		harness: section.harness,
		id: section.id,
		label: section.label,
		templateId: section.templateId,
	}));

	return (
		<div className="flex size-full flex-col overflow-hidden">
			{/* Workspace: composed letter (cards + editors) and the agent */}
			<div
				className={cn(
					"grid min-h-0 flex-1 grid-cols-1 gap-4 overflow-y-auto p-4 lg:overflow-hidden",
					"lg:grid-cols-[minmax(0,1fr)_22rem] xl:grid-cols-[minmax(0,1fr)_26rem]",
				)}
			>
				{/* Left: composed letter — each field's card beside its editor */}
				<div className="space-y-6 lg:h-full lg:overflow-y-auto lg:pr-1">
					{/* Title (left) + privacy notice (right) */}
					<div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
						<div className="flex min-w-0 items-center gap-3">
							<div className="shrink-0 rounded-full bg-solarized-blue/10 p-2">
								<FileText className="h-5 w-5 text-solarized-blue" />
							</div>
							<div className="min-w-0">
								<h1 className="truncate font-bold text-lg text-primary">{title}</h1>
								<p className="truncate text-muted-foreground text-sm">{description}</p>
							</div>
						</div>
						<div className="rounded-lg border border-solarized-red/20 bg-solarized-red/5 px-3 py-2 text-xs lg:max-w-sm">
							<p className="text-solarized-red">
								⚠️ <strong>Datenschutz:</strong> Keine privaten Patientendaten eingeben – nur
								anonymisierte Daten verwenden.
							</p>
						</div>
					</div>

					{/* Field rows: info card + editor side by side */}
					<div className="space-y-6">
						{sections.map((section) => {
							const sectionChangeHandler = sectionChangeHandlers[section.id];
							if (!sectionChangeHandler) {
								return null;
							}

							return (
								<div className="flex flex-col gap-4 lg:flex-row lg:items-start" key={section.id}>
									<DoctorsNoteFieldCard className={FIELD_CARD_CLASS} config={section} />
									<div className="min-w-0 flex-1">
										<DoctorsNoteSection
											config={section}
											context={getContextForSection(section.id)}
											disabled={disabled}
											minHeight={PAIR_MIN_HEIGHT}
											onChange={sectionChangeHandler}
											onProposalResolved={proposalResolvedHandlers[section.id]}
											onSuggestionValueChange={handleSuggestionValueChange}
											proposal={agentProposals[section.id] ?? null}
											value={sectionValues[section.id] || ""}
										/>
									</div>
								</div>
							);
						})}
					</div>

					{/* Footer hint */}
					<div className="flex items-center justify-center gap-4 text-muted-foreground text-xs">
						<div className="flex items-center gap-1.5">
							<Kbd>⌘↵</Kbd>
							<span>zum Verbessern</span>
						</div>
					</div>
				</div>

				{/* Right: agent panel */}
				<div className="lg:h-full lg:overflow-hidden">
					<DoctorsNoteAgentPanel
						disabled={disabled}
						initialContext={initialAgentContext}
						onProposeEdit={handleAgentPropose}
						sections={agentSections}
					/>
				</div>
			</div>
		</div>
	);
};
