/**
 * Ed25519 license-verification public key (raw, base64url).
 *
 * This is the PUBLIC half of the license signing keypair and is safe to commit.
 * It is generated by `scripts/license-keygen.ts`. The matching private key is
 * never committed and is used only by the offline `scripts/sign-license.ts`
 * minting CLI.
 *
 * Regenerating the keypair invalidates every license key already issued.
 */
export const LICENSE_PUBLIC_KEY = "O1pG4Hv3vbzcmR2WNC8Iuq-50JqECT_R_b5GDjPo5zw";
