import "server-only";

// Re-export useful Drizzle utilities
export {
	and,
	asc,
	avg,
	count,
	desc,
	eq,
	gt,
	gte,
	inArray,
	isNotNull,
	isNull,
	like,
	lt,
	lte,
	ne,
	notInArray,
	or,
	sql,
	sum,
} from "drizzle-orm";
// Export only the database type here to avoid eager database bootstrap.
export type { Database } from "./client";
// Re-export schema tables for direct access
export {
	account,
	accountRelations,
	aiDefaults,
	aiModel,
	aiModelRelations,
	aiProvider,
	aiProviderRelations,
	aiScribeFormConfig,
	aiScribeFormConfigRelations,
	aiScribeWorkspace,
	aiScribeWorkspaceRelations,
	contextTransfer,
	documentTemplate,
	documentTemplateRelations,
	favourites,
	favouritesRelations,
	session,
	sessionRelations,
	subscription,
	subscriptionRelations,
	template,
	templateCollection,
	templateCollectionRelations,
	templateCollectionTemplate,
	templateCollectionTemplateRelations,
	templateRelations,
	textSnippet,
	textSnippetRelations,
	usageEvent,
	usageEventRelations,
	usageObservation,
	usageObservationRelations,
	usageTrace,
	usageTraceRelations,
	user,
	userAiProvider,
	userAiProviderRelations,
	userRelations,
	verification,
} from "./schema";

// Re-export types for backward compatibility
export type {
	Account,
	AiDefaults,
	AiModel,
	AiProvider,
	AiScribeFormConfig,
	AiScribeWorkspace,
	ContextTransfer,
	DocumentTemplate,
	Favourite,
	NewAccount,
	NewAiDefaults,
	NewAiModel,
	NewAiProvider,
	NewAiScribeFormConfig,
	NewAiScribeWorkspace,
	NewContextTransfer,
	NewDocumentTemplate,
	NewFavourite,
	NewSession,
	NewSubscription,
	NewTemplate,
	NewTemplateCollection,
	NewTemplateCollectionTemplate,
	NewTextSnippet,
	NewUsageEvent,
	NewUsageObservation,
	NewUsageTrace,
	NewUser,
	NewUserAiProvider,
	NewVerification,
	Session,
	Subscription,
	Template,
	TemplateCollection,
	TemplateCollectionTemplate,
	TextSnippet,
	UsageEvent,
	User,
	UserAiProvider,
	Verification,
} from "./types";
