import { PHYSICAL_EXAM_SYSTEM_ROLE } from "./physical-exam/system-role";

const PHYSICAL_EXAM_SYSTEM_PROMPT_PARTS = [PHYSICAL_EXAM_SYSTEM_ROLE];

export const PHYSICAL_EXAM_SYSTEM_PROMPT = PHYSICAL_EXAM_SYSTEM_PROMPT_PARTS.join("\n\n");
